name: Tests
#Tests action
on:
    push:
        branches:
            - main

jobs:
    tests:
        strategy:
            matrix:
                node-version: [12.x, 13.x, 14.x]
                platform: [ubuntu-latest, macos-latest, windows-latest]

        ## Defines the platform for each test run
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/checkout@v2
            - run: yarn install
            - run: yarn test
