name: Tests
#Tests action
on:
    push:
        branches:
            - main

jobs:
    tests:
        strategy:
            ## this will contain a matrix of all of the combinations
            ## we wish to test again:
            matrix:
                node-version: [12.x, 13.x, 14.x]
                platform: [ubuntu-latest, macos-latest, windows-latest]

        ## Defines the platform for each test run
        runs-on: ${{ matrix.platform }}

        steps:
            - name: Install Node
                - uses: actions/setup-node@v2
                  with:
                      node-version: ${{ matrix.node-version }}
            
            - name: Checkout Code
                - uses: actions/checkout@v2
            
            - name: Run Tests
                - run: yarn install
                - run: yarn test
